/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controller.UsuarioController;
import DAO.UsuarioDAO;
import Pojo.Usuario;
import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.json.Json;
import javax.json.JsonObject;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
/**
 *
 * @author ASUS555
 */
public class UsuariosForm extends javax.swing.JFrame {

   
     UsuarioController us = new UsuarioController();
     UsuarioDAO DAO = new UsuarioDAO();
     DefaultTableModel model;
    
    public UsuariosForm() {
        initComponents();
        
        
        List<Usuario> lista = us.listUsuario();
        // List<Usuario> lista = new ArrayList<>();
        //lista.add(DAO.FindByDoc("25698455"));
        
        model = (DefaultTableModel) tbl_usuario.getModel();
     
        Iterator it = lista.iterator();
        Object RowTable[] = new Object[7];
       

        while(it.hasNext()){
              
         Usuario user = (Usuario) it.next();
         RowTable[0] =  user.getId_usuario();
         RowTable[1] =  user.getNombre();
         RowTable[2] =  user.getApellido1()+" "+user.getApellido2();
         RowTable[3] =  user.getNroDoc();
         RowTable[4] =  user.getCategoria();
         RowTable[5] =  user.getMail();
         RowTable[6] =  user.getEstado();
         model.addRow(RowTable);
        }
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellidos", "DNI", "Categoria", "mail", "Estado"
            }
        ));
        tbl_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_usuarioMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_usuario);

        jLabel1.setText("Buscar:");

        txt_Buscar.setText("Nombre, Apellido, DNI.");
        txt_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuarioMouseClicked
        String cadena="";
        int row = tbl_usuario.rowAtPoint(evt.getPoint());
        
        if (row >= 0 && tbl_usuario.isEnabled())
        {
            
            cadena = tbl_usuario.getValueAt(row, 0).toString();
           /* for (int i=0; i < tbl_usuario.getColumnCount();i++)
            {
               cadena=cadena + " " +  tbl_usuario.getValueAt(row,i).toString();
            }*/
        }

        //JOptionPane.showMessageDialog(null, cadena);
        CapturarHuella cp = new CapturarHuella();
        cp.set_ID(cadena);
        //JOptionPane.showMessageDialog(null,   cp.getId_Usuario());
        cp.setVisible(true);
        cp.EventoInicializar();
        //this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_tbl_usuarioMouseClicked

    private void tbl_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_usuarioMousePressed

    
    
     //Buscar Usuarios 
    private void filter(String query){
        TableRowSorter<DefaultTableModel> filter = new TableRowSorter<DefaultTableModel>(model);
        tbl_usuario.setRowSorter(filter);
      
        filter.setRowFilter(RowFilter.regexFilter(query));
        
        if(tbl_usuario.getRowCount() == 0){
            filter.setRowFilter(RowFilter.regexFilter(query.toLowerCase()));
                if(tbl_usuario.getRowCount() == 0){
                    filter.setRowFilter(RowFilter.regexFilter(query.toUpperCase()));
                        if(tbl_usuario.getRowCount() == 0){
                            String capitalize = query.substring(0, 1).toUpperCase() + query.substring(1);
                            filter.setRowFilter(RowFilter.regexFilter(capitalize));
                        }
                }
        }
    }
    private void txt_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarKeyReleased
     filter(txt_Buscar.getText());
    }//GEN-LAST:event_txt_BuscarKeyReleased

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_usuario;
    private javax.swing.JTextField txt_Buscar;
    // End of variables declaration//GEN-END:variables
}
