/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controller.UsuarioController;
import DAO.UsuarioDAO;
import Pojo.Usuario;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author ASUS555
 */
public class UsuariosForm extends javax.swing.JFrame {

   
     UsuarioController us = new UsuarioController();
     UsuarioDAO DAO = new UsuarioDAO();
     DefaultTableModel model;
    
    public UsuariosForm() {
        initComponents();
                
        List<Usuario> lista = us.listUsuario();
        
        model = (DefaultTableModel) tbl_usuario.getModel();
        model.setNumRows(0);
        Iterator it = lista.iterator();
        Object RowTable[] = new Object[7];
       
        //Recorre la lista de Usuarios y setea los valores a la tabla.
        while(it.hasNext()){                         
            Usuario user = (Usuario) it.next();
            RowTable[0] =  user.getId_usuario();
            RowTable[1] =  user.getApellido1()+" "+user.getApellido2();
            RowTable[2] =  user.getNombre();
            RowTable[3] =  user.getNroDoc();
            RowTable[4] =  user.getCategoria();
            RowTable[5] =  user.getMail();
            RowTable[6] =  user.getEstado();
            model.addRow(RowTable);
        }
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_listar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Usuarios");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setSize(new java.awt.Dimension(800, 600));

        tbl_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Apellidos", "Nombre", "DNI", "Categoria", "mail", "Estado"
            }
        ));
        tbl_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_usuarioMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_usuario);

        jLabel1.setText("Buscar:");

        txt_Buscar.setText("Nombre, Apellido, DNI.");
        txt_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_BuscarMouseClicked(evt);
            }
        });
        txt_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarKeyReleased(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_listar.setText("Listar Usuarios");
        btn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuarioMouseClicked
        
        String cadena="";
        int row = tbl_usuario.rowAtPoint(evt.getPoint());
        
        if (row >= 0 && tbl_usuario.isEnabled())
        {
            //Obtenemos el ID del usuario Seleccionado.
            cadena = tbl_usuario.getValueAt(row, 0).toString();
           
        }
        
        //Pasamos parametros a la otra vista.
        CapturarHuella cp = new CapturarHuella();
        cp.set_ID(cadena);
        cp.setVisible(true);
        cp.EventoInicializar();
        this.dispose();
        
    }//GEN-LAST:event_tbl_usuarioMouseClicked

    private void tbl_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_usuarioMousePressed

    
    
     //Buscar Usuarios 
    private void filter(String query){
        TableRowSorter<DefaultTableModel> filter = new TableRowSorter<DefaultTableModel>(model);
        tbl_usuario.setRowSorter(filter);
      
        filter.setRowFilter(RowFilter.regexFilter(query));
        
        if(tbl_usuario.getRowCount() == 0){
            filter.setRowFilter(RowFilter.regexFilter(query.toLowerCase()));
                if(tbl_usuario.getRowCount() == 0){
                    filter.setRowFilter(RowFilter.regexFilter(query.toUpperCase()));
                        if(tbl_usuario.getRowCount() == 0){
                            String capitalize = query.substring(0, 1).toUpperCase() + query.substring(1);
                            filter.setRowFilter(RowFilter.regexFilter(capitalize));
                        }
                }
        }
    }
    private void txt_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarKeyReleased
     filter(txt_Buscar.getText());
    }//GEN-LAST:event_txt_BuscarKeyReleased

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
            
       List<Usuario> lista = us.FindUser(txt_Buscar.getText());
                
        if(lista == null){
            JOptionPane.showMessageDialog(this, "No se pudo encontrar el Usuario.", "Buscar Usuario", JOptionPane.PLAIN_MESSAGE, new ImageIcon(this.getClass().getResource("/Images/icono_user.png")));
        }else{
                model = (DefaultTableModel) tbl_usuario.getModel();
                model.setNumRows(0);
                Iterator it = lista.iterator();
                Object RowTable[] = new Object[7];

                //Recorre la lista de Usuarios y setea los valores a la tabla.
                while(it.hasNext()){                         
                    Usuario user = (Usuario) it.next();
                    RowTable[0] =  user.getId_usuario();
                    RowTable[1] =  user.getApellido1()+" "+user.getApellido2();
                    RowTable[2] =  user.getNombre();
                    RowTable[3] =  user.getNroDoc();
                    RowTable[4] =  user.getCategoria();
                    RowTable[5] =  user.getMail();
                    RowTable[6] =  user.getEstado();
                    model.addRow(RowTable);
                }
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarActionPerformed
       
        
        List<Usuario> lista = us.listUsuario();
        model = (DefaultTableModel) tbl_usuario.getModel();
        model.setNumRows(0);
        Iterator it = lista.iterator();
        Object RowTable[] = new Object[7];
       
        //Recorre la lista de Usuarios y setea los valores a la tabla.
        while(it.hasNext()){                         
            Usuario user = (Usuario) it.next();
            RowTable[0] =  user.getId_usuario();
            RowTable[1] =  user.getApellido1()+" "+user.getApellido2();
            RowTable[2] =  user.getNombre();
            RowTable[3] =  user.getNroDoc();
            RowTable[4] =  user.getCategoria();
            RowTable[5] =  user.getMail();
            RowTable[6] =  user.getEstado();
            model.addRow(RowTable);
        }
        txt_Buscar.setText(null);
    }//GEN-LAST:event_btn_listarActionPerformed

    private void txt_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_BuscarMouseClicked
        txt_Buscar.setText("");
    }//GEN-LAST:event_txt_BuscarMouseClicked

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_listar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_usuario;
    private javax.swing.JTextField txt_Buscar;
    // End of variables declaration//GEN-END:variables
}
